name: Inference Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python src/train.py
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model_train.pkl

  inference:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model
          path: .
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run inference
        run: python src/inference.py
