name: Full ML Pipeline
on:
  push:
    branches: [ inference_branch ]
  pull_request:
    branches: [ inference_branch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest tests/ -v --tb=short

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: |
          cd src
          python train.py
      - uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: src/model_trained.pkl

  inference:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: src/
      - run: |
          cd src
          python inference.py
