name: Train Model
on:
  push:
    branches: [ classification_branch ]
  pull_request:
    branches: [ classification_branch ]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run training job
        run: |
          cd src
          python train.py
      - name: Archive trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: src/model_trained.pkl